[package]
name = "clawin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
clawin-bootstrap = { path = "../clawin-bootstrap" }

[dev-dependencies]
assert_cmd.workspace = true
cargo_metadata.workspace = true
